services:
  db:
    container_name: db
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - ./config/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c fsync=0 -c full_page_writes=0
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"
  api01: &api
    container_name: api01
    hostname: api01
    build:
      context: ./src
      dockerfile: PaymentProcessorMiddleware/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:80
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "9999:80"
    networks:
      - backend
      - payment-processor
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '125MB'
  api02:
    <<: *api 
    container_name: api02
    hostname: api02
    ports:
      - "10000:80"
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true


