services:
  api01: &api
    container_name: api01
    hostname: api01
    build:
      context: ./src
      dockerfile: PaymentProcessorMiddleware/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:80
    ports:
      - "9999:80"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '175MB'
  api02:
    <<: *api 
    container_name: api02
    hostname: api02
    ports:
      - "10000:80"
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true


